/run/initialize

/gps/particle gamma
/gps/pos/type Point
/gps/pos/confine Plastikzylinder
/gps/pos/centre 0. 0. -17.35761899802374 mm
/gps/ang/type iso

/gps/ene/type Gauss
/gps/ene/mono 0.661657 MeV

# Set the output filename to contain the simulated energy in an uniform number format and disable appendage of additional file IDs
#/utr/setUseFilenameID False
#/utr/appendZerosToVar E {E} 2
#/utr/setFilename Efficiency_{E}_MeV

# Never simulate more than 2^32= 4294967296 particles using /run/beamOn, since this causes an overflow in the random number seed, giving you in principle the same results over and over again.
# In such cases execute the same simulation multiple times instead.
/run/beamOn 100